### PR TITLE
DontTakeItSerious

### PR DESCRIPTION
**Pull request by DontTakeItSerious**
It's Lithuanian version of your plugin.

### CODE REVIEW

**Comment by javascripto** [comment]
Thanks! One left then, swedish.

**Comment by DontTakeItSerious** [comment]
Hello, I've made a custom basicbot project. How to upload it to the plug.dj community now?

<div>-------- Originali žinutė --------</div><div>Nuo: "javascript:" <notifications@github.com> </div><div>Data:2016-06-04  17:58  (GMT+02:00) </div><div>Kam: basicBot/source <source@noreply.github.com> </div><div>Kopija: DontTakeItSerious <sgriskus2002@gmail.com>, Author <author@noreply.github.com> </div><div>Tema: Re: [basicBot/source] DontTakeItSerious (#110) </div><div>
</div>Thanks! One left then, swedish.

**Comment by javascripto** [comment]
Make link for it and try to connect with bot.

**Comment by ItzLevvie** [comment]
You edited the wrong file.

**Comment by DontTakeItSerious** [comment]
Yeah, I know, I've edited English version to the Lithuanian one just in
case it would easier to install everything, I wouldn't even need to change
almost anything.
Now what about the link? How can I make it? Sorry, I am a newbie at this :D

**Comment by DontTakeItSerious** [comment]
I mean, I already understand how to make the link, but how to make it to
the right language set?

2016-06-05 17:27 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:

> Yeah, I know, I've edited English version to the Lithuanian one just in
> case it would easier to install everything, I wouldn't even need to change
> almost anything.
> Now what about the link? How can I make it? Sorry, I am a newbie at this :D
>

**Comment by DontTakeItSerious** [comment]
I recognised my mistake (I had to make it to Custom patch, not the source),
but i still don't really know what to do next :D

**Comment by DontTakeItSerious** [comment]
It's here lol https://github.com/DontTakeItSerious/custom/

2016-06-05 17:59 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:

> I recognised my mistake (I had to make it to Custom patch, not the
> source), but i still don't really know what to do next :D
>

**Comment by DontTakeItSerious** [comment]
Is that everything ok with this?
https://github.com/DontTakeItSerious/custom/blob/master/extension.js

2016-06-05 18:01 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:

> It's here lol https://github.com/DontTakeItSerious/custom/
>
> 2016-06-05 17:59 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:
>
>> I recognised my mistake (I had to make it to Custom patch, not the
>> source), but i still don't really know what to do next :D
>>
>
>

**Comment by DontTakeItSerious** [comment]
I think i got everything, but something is wrong with
this: javascript:(function(){$.getScript('
https://raw.githubusercontent.com/DontTakeItSerious/custom/master/extension.js');})(
);

2016-06-05 18:20 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:

> Is that everything ok with this?
> https://github.com/DontTakeItSerious/custom/blob/master/extension.js
>
> 2016-06-05 18:01 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:
>
>> It's here lol https://github.com/DontTakeItSerious/custom/
>>
>> 2016-06-05 17:59 GMT+03:00 Šarūnas Griškus <sgriskus2002@gmail.com>:
>>
>>> I recognised my mistake (I had to make it to Custom patch, not the
>>> source), but i still don't really know what to do next :D
>>>
>>
>>
>

**Comment by javascripto** [comment]
https://github.com/javascripto/basicBot-v2 look how mine is made and try to remake it to your self

**Comment by DontTakeItSerious** [comment]
I guess it's not possible to set the Bot (your made bot v2) to Lithuanian
language, In languages which are available it shows the list from BasicBot
v1 language list.

2016-06-05 21:01 GMT+03:00 javascript: <notifications@github.com>:

**Comment by DontTakeItSerious** [comment]
It says it's changed, but there's no effect in the language. I make a
simple command like !roulette and it's still the same, english text.

**Comment by javascripto** [comment]
http://javascripto.github.io/basicBot-v2/
Use LT bot and before doing that type in this in console: localStorage.clear() and refresh, then activate LT bot and there you go.

**Comment by DontTakeItSerious** [comment]
Thanks very much. It worked :)

2016-06-06 12:04 GMT+03:00 javascript: <notifications@github.com>:

**Comment by javascripto** [comment]
No problem :+1: :100:

**Pull request closed without merging**
